---

- hosts: localhost
  vars:
    # should be passed in the CLI like `--extra-vars "version=1.23.45 branch=master"`
    version: 0-dev # e.g. 0.78
    branch: master # any existing branch on Github
    release: STABLE # STABLE, RELEASE_CANDIDATE, HOTFIX, and SECURITY are valid options
    tag_name: "v{{ version}}"
    project: "ceph"
    clean: true # if re-doing a deployment this deletes the remote branch in Jenkin's git repo
    force_dch: false # if coming from a rc and wanting to release a stable you need to force dch
    debemail: ceph-maintainers@ceph.com
    debfullname: "Ceph Release Team"
  roles:
    - { role: ceph-release, when: "project == 'ceph'" }
    - { role: ceph-deploy-release, when: "project == 'ceph-deploy'" }
    - { role: remoto-release, when: "project == 'remoto'" }
